// <auto-generated />
using InsideIASI.DataAccess.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InsideIASI.DataAccess.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20230508153117_PointOfInterestOpeningHoursRelationship")]
    partial class PointOfInterestOpeningHoursRelationship
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InsideIASI.DataAccess.Entities.OpeningHour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClosingTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Day")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OpeningTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PointOfInterestId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PointOfInterestId");

                    b.ToTable("OpeningHours");
                });

            modelBuilder.Entity("InsideIASI.DataAccess.Entities.PointOfInterest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Info0")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Info1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Info2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Info3")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PointsOfInterest");
                });

            modelBuilder.Entity("InsideIASI.DataAccess.Entities.OpeningHour", b =>
                {
                    b.HasOne("InsideIASI.DataAccess.Entities.PointOfInterest", "PointOfInterest")
                        .WithMany("OpeningHours")
                        .HasForeignKey("PointOfInterestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PointOfInterest");
                });

            modelBuilder.Entity("InsideIASI.DataAccess.Entities.PointOfInterest", b =>
                {
                    b.Navigation("OpeningHours");
                });
#pragma warning restore 612, 618
        }
    }
}
